name: Test Action

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test CI run
      run: |
        echo command one
        false
        echo command two

